# Generated by Django 4.2.4 on 2023-08-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoepro_app', '0002_remove_lineitems_pk_remove_notifications_pk_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItems',
            new_name='LineItem',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderNotes',
            new_name='OrderNote',
        ),
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductTaxonomies',
            new_name='ProductTaxonomie',
        ),
        migrations.RenameModel(
            old_name='ProductTaxonomyTerms',
            new_name='ProductTaxonomyTerm',
        ),
        migrations.RenameModel(
            old_name='ProductTerms',
            new_name='ProductTerm',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
