# Generated by Django 4.2.4 on 2023-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoepro_app', '0003_rename_lineitems_lineitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttaxonomie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
