# Generated by Django 4.2.4 on 2023-08-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoepro_app', '0004_alter_producttaxonomie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttaxonomyterm',
            name='ptt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoepro_app.producttaxonomie'),
        ),
        migrations.AlterField(
            model_name='producttaxonomyterm',
            name='ptt_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
